### ISSUE TITLE
CI Deployment

### ISSUE THREAD

**Issue by bastianccm** [AOEpeople/techradar#1]
Instead of travis we should use github actions.
Tasks: `yarn aoe_technology radar`, then deploy to S3.

Reference from Travis

```yaml
language: node_js
node_js: node
install: yarn
script: yarn aoe_technology_radar
cache: yarn
deploy:
  - provider: s3
    # encrypted keys:
    access_key_id:
      secure: IqwsUtTxYBprni5jMtDFZxXzOwes6aTOKFcyEK6bN2uDjDTxbEf8Aub41I56dkzmCuxxN0233PktgTm8l3z62iK+dDbC/rwmBMBU4fVgtlehTt+wqaaJx1fyTytm2sgIXV5rsRCH+XUY5dfPEkv1FLYIDbw+YJ8Fm1vIEWQ7x1ROi1b59GuYwUSOq1ZQEH4lEfcsSJu4wLKuRjhGagHcucZ77Z+DBvwktwqe1g1L5S4TmFXCSaYV7ceYu9zRtzIiyN9AK6HAKXqptKJK541oYRaCOo3fPPkShKCYqFZDgUCd8ele4G1JaJObii7NznkpBsaZjhT1Yt1risf0hGZFSL9BPKRbBuvBpvoJx7t41ppo5CUot37bontiJ/tDJ1QKl34P5yqPatFKQnM6nlR3K+IW0EdNL1XcYLfKYkxh1loUasy5Zf26vC7j+Q9K2jubidd3YcqKWcC0VAttvB6hw60hQ3XdE9EcH5OzvhDg1Ju5zmq4VrHDL8ymHgRmZzQPtdpon5S0j9Z45YkTPqc2XGWJTuq1ED7Hq3wO/6ry4+roAeAmZ1qXLww+LWcm/Yki9/y++e19+JxhSFNWEZK4kn7K7TquumSF6gP7ukJj8TgG4kXRZs7vcl0J4nYJA/qYQFMbVfw8SgdXT/zLNQaK6RNH3x3uOMfl3VDt3sAY2rk=
    secret_access_key:
      secure: f8ThXSrY6huRhUteqgcFm1e21DPOFcSlNq6SzmHEPbXn9XkzyQthjtZk5W1xboww+TJCs8um+mZ7liebBntF6YyS/2I/uA/XX957K6qpW9x3zOvqoEkhurJ8pJQA6HP0lJP2lwiDvIgytd1VafzPw1iqQjQVqblpuGodzFR/i17pISdj1NJD5HP6wNHCAukjPiYAhXDxuxdCb042fYtXE75MiidIwOcfBjmShAO1fOBxtHq9nyUg7esbMJavx6QAtXVxBuqOAPCU8rtJH7oq4b8FNuH1QtByAUqIG3dgXMdCltKRt0FP6+c5gpO5rWaGD0XkVPxhCo/XJcAbpNKdYXBRQtp5Ki2PAnnOJVJ5fp6raXNI5tereyIzYQPkoOrLruB9tWtCiFd0qHTuiqe4xVfTQK7EGxe99cKl1axxFDVeLayNOrsy9J1zob7i/HmGsgh2UT32+ao2TOn0IKx/5y7njyXpaBTokIk8qJlb0wIuT2R5LHfzKFK2EoI+v0EWWiZXHqSpUYpPMCF6QUNIotWm+61M8yHx9Z2/XzllZXEFA+ZAFOSTeNU8xCbZ3hhdIN6x8XQ23Qi1xVVfE1DT8ZrTmCzLPoQwvxnzR4wN157tbHfYFOiLc2cORv7HptdeipQhdUXBAD+7C5aGQxbu4pi7GNy0vKiaaNSG8RdZjIg=
    bucket: techradar.aoe.com
    skip_cleanup: true
    acl: public_read
    region: eu-central-1
    local_dir: dist
    detect_encoding: true
    on:
      branch: master
  - provider: s3
    # encrypted keys:
    access_key_id:
      secure: IqwsUtTxYBprni5jMtDFZxXzOwes6aTOKFcyEK6bN2uDjDTxbEf8Aub41I56dkzmCuxxN0233PktgTm8l3z62iK+dDbC/rwmBMBU4fVgtlehTt+wqaaJx1fyTytm2sgIXV5rsRCH+XUY5dfPEkv1FLYIDbw+YJ8Fm1vIEWQ7x1ROi1b59GuYwUSOq1ZQEH4lEfcsSJu4wLKuRjhGagHcucZ77Z+DBvwktwqe1g1L5S4TmFXCSaYV7ceYu9zRtzIiyN9AK6HAKXqptKJK541oYRaCOo3fPPkShKCYqFZDgUCd8ele4G1JaJObii7NznkpBsaZjhT1Yt1risf0hGZFSL9BPKRbBuvBpvoJx7t41ppo5CUot37bontiJ/tDJ1QKl34P5yqPatFKQnM6nlR3K+IW0EdNL1XcYLfKYkxh1loUasy5Zf26vC7j+Q9K2jubidd3YcqKWcC0VAttvB6hw60hQ3XdE9EcH5OzvhDg1Ju5zmq4VrHDL8ymHgRmZzQPtdpon5S0j9Z45YkTPqc2XGWJTuq1ED7Hq3wO/6ry4+roAeAmZ1qXLww+LWcm/Yki9/y++e19+JxhSFNWEZK4kn7K7TquumSF6gP7ukJj8TgG4kXRZs7vcl0J4nYJA/qYQFMbVfw8SgdXT/zLNQaK6RNH3x3uOMfl3VDt3sAY2rk=
    secret_access_key:
      secure: f8ThXSrY6huRhUteqgcFm1e21DPOFcSlNq6SzmHEPbXn9XkzyQthjtZk5W1xboww+TJCs8um+mZ7liebBntF6YyS/2I/uA/XX957K6qpW9x3zOvqoEkhurJ8pJQA6HP0lJP2lwiDvIgytd1VafzPw1iqQjQVqblpuGodzFR/i17pISdj1NJD5HP6wNHCAukjPiYAhXDxuxdCb042fYtXE75MiidIwOcfBjmShAO1fOBxtHq9nyUg7esbMJavx6QAtXVxBuqOAPCU8rtJH7oq4b8FNuH1QtByAUqIG3dgXMdCltKRt0FP6+c5gpO5rWaGD0XkVPxhCo/XJcAbpNKdYXBRQtp5Ki2PAnnOJVJ5fp6raXNI5tereyIzYQPkoOrLruB9tWtCiFd0qHTuiqe4xVfTQK7EGxe99cKl1axxFDVeLayNOrsy9J1zob7i/HmGsgh2UT32+ao2TOn0IKx/5y7njyXpaBTokIk8qJlb0wIuT2R5LHfzKFK2EoI+v0EWWiZXHqSpUYpPMCF6QUNIotWm+61M8yHx9Z2/XzllZXEFA+ZAFOSTeNU8xCbZ3hhdIN6x8XQ23Qi1xVVfE1DT8ZrTmCzLPoQwvxnzR4wN157tbHfYFOiLc2cORv7HptdeipQhdUXBAD+7C5aGQxbu4pi7GNy0vKiaaNSG8RdZjIg=
    bucket: techradar-next.aoe.com
    skip_cleanup: true
    acl: public_read
    region: eu-central-1
    local_dir: dist
    detect_encoding: true
    on:
      branch: v3
```
